export type Country = { code: string; name: string; flagUrl: string };

function flagUrl(code: string) {
  return `https://flagcdn.com/${code.toLowerCase()}.svg`;
}

const RAW_COUNTRIES: { code: string; name: string }[] = [
  { code: "AU", name: "Австрали" },
  { code: "AT", name: "Австри" },
  { code: "AZ", name: "Азербайжан" },
  { code: "AL", name: "Албани" },
  { code: "DZ", name: "Алжир" },
  { code: "AI", name: "Ангилла" },
  { code: "AO", name: "Ангол" },
  { code: "AD", name: "Андорра" },
  { code: "AG", name: "Антигуа Барбуда" },
  { code: "AR", name: "Аргентин" },
  { code: "AM", name: "Армен" },
  { code: "AF", name: "Афганистан" },
  { code: "BS", name: "Багам" },
  { code: "BD", name: "Бангладеш" },
  { code: "BB", name: "Барбадос" },
  { code: "BH", name: "Бахрейн" },
  { code: "BY", name: "Беларусь" },
  { code: "BZ", name: "Белиз" },
  { code: "BE", name: "Бельги" },
  { code: "BJ", name: "Бенин" },
  { code: "BG", name: "Болгар" },
  { code: "BO", name: "Боливи" },
  { code: "BA", name: "Босни Герцеговина" },
  { code: "BW", name: "Ботсвана" },
  { code: "BR", name: "Бразил" },
  { code: "BN", name: "Бруней" },
  { code: "BF", name: "Буркина Фасо" },
  { code: "BI", name: "Бурунди" },
  { code: "BT", name: "Бутан" },
  { code: "VA", name: "Ватикан" },
  { code: "VU", name: "Вануату" },
  { code: "HU", name: "Венгр" },
  { code: "VE", name: "Венесуэл" },
  { code: "VN", name: "Вьетнам" },
  { code: "HT", name: "Гаити" },
  { code: "GY", name: "Гайана" },
  { code: "GM", name: "Гамби" },
  { code: "GH", name: "Гана" },
  { code: "GT", name: "Гватемал" },
  { code: "GN", name: "Гвиней" },
  { code: "GW", name: "Гвиней-Бисау" },
  { code: "DE", name: "Герман" },
  { code: "HN", name: "Гондурас" },
  { code: "GD", name: "Гренада" },
  { code: "GR", name: "Грек" },
  { code: "GE", name: "Грузи" },
  { code: "DK", name: "Дани" },
  { code: "DM", name: "Доминика" },
  { code: "DO", name: "Доминикан" },
  { code: "EG", name: "Египет" },
  { code: "ZM", name: "Замби" },
  { code: "ZW", name: "Зимбабве" },
  { code: "IL", name: "Израиль" },
  { code: "IN", name: "Энэтхэг" },
  { code: "ID", name: "Индонез" },
  { code: "JO", name: "Иордан" },
  { code: "IQ", name: "Ирак" },
  { code: "IR", name: "Иран" },
  { code: "IE", name: "Ирланд" },
  { code: "IS", name: "Исланд" },
  { code: "ES", name: "Испани" },
  { code: "IT", name: "Итали" },
  { code: "YE", name: "Йемен" },
  { code: "CV", name: "Кабо Верде" },
  { code: "KZ", name: "Казахстан" },
  { code: "KH", name: "Камбож" },
  { code: "CM", name: "Камерун" },
  { code: "CA", name: "Канад" },
  { code: "QA", name: "Катар" },
  { code: "KE", name: "Кени" },
  { code: "CY", name: "Кипр" },
  { code: "KG", name: "Киргизстан" },
  { code: "KI", name: "Кирибати" },
  { code: "CO", name: "Колумб" },
  { code: "KM", name: "Коморос" },
  { code: "CR", name: "Коста-Рика" },
  { code: "CI", name: "Кот-д'Ивуар" },
  { code: "CU", name: "Куба" },
  { code: "KW", name: "Кувейт" },
  { code: "LA", name: "Лаос" },
  { code: "LV", name: "Латви" },
  { code: "LS", name: "Лесото" },
  { code: "LR", name: "Либери" },
  { code: "LB", name: "Ливан" },
  { code: "LY", name: "Ливи" },
  { code: "LT", name: "Литва" },
  { code: "LI", name: "Лихтенштейн" },
  { code: "LU", name: "Люксембург" },
  { code: "MU", name: "Маврикий" },
  { code: "MR", name: "Мавритани" },
  { code: "MG", name: "Мадагаскар" },
  { code: "MW", name: "Малави" },
  { code: "MY", name: "Малайз" },
  { code: "ML", name: "Мали" },
  { code: "MV", name: "Мальдив" },
  { code: "MT", name: "Мальта" },
  { code: "MA", name: "Марокко" },
  { code: "MH", name: "Маршалл" },
  { code: "MX", name: "Мексик" },
  { code: "FM", name: "Микронез" },
  { code: "MZ", name: "Мозамбик" },
  { code: "MD", name: "Молдав" },
  { code: "MC", name: "Монако" },
  { code: "MN", name: "Монгол" },
  { code: "MM", name: "Мьянмар" },
  { code: "NA", name: "Намиби" },
  { code: "NR", name: "Науру" },
  { code: "NP", name: "Непал" },
  { code: "NE", name: "Нигер" },
  { code: "NG", name: "Нигери" },
  { code: "NL", name: "Нидерланд" },
  { code: "NI", name: "Никарагуа" },
  { code: "NU", name: "Ниуэ" },
  { code: "NO", name: "Норвеги" },
  { code: "OM", name: "Оман" },
  { code: "PK", name: "Пакистан" },
  { code: "PW", name: "Палау" },
  { code: "PS", name: "Палестин" },
  { code: "PA", name: "Панам" },
  { code: "PG", name: "Папуа Шинэ Гвиней" },
  { code: "PY", name: "Парагвай" },
  { code: "PE", name: "Перу" },
  { code: "PL", name: "Польш" },
  { code: "PT", name: "Португал" },
  { code: "RU", name: "Орос" },
  { code: "RW", name: "Руанда" },
  { code: "RO", name: "Румын" },
  { code: "US", name: "АНУ" },
  { code: "SV", name: "Сальвадор" },
  { code: "SM", name: "Сан-Марино" },
  { code: "ST", name: "Сан-Томе Принсипи" },
  { code: "SA", name: "Саудын Араб" },
  { code: "SZ", name: "Свазиланд" },
  { code: "SC", name: "Сейшел" },
  { code: "SN", name: "Сенегал" },
  { code: "VC", name: "Сент-Винсент Гренадин" },
  { code: "KN", name: "Сент-Китс Невис" },
  { code: "LC", name: "Сент-Люсия" },
  { code: "RS", name: "Серби" },
  { code: "SG", name: "Сингапур" },
  { code: "SY", name: "Сири" },
  { code: "SK", name: "Словак" },
  { code: "SI", name: "Словени" },
  { code: "SB", name: "Соломон" },
  { code: "SO", name: "Сомали" },
  { code: "SD", name: "Судан" },
  { code: "SR", name: "Суринам" },
  { code: "SL", name: "Сьерра-Леоне" },
  { code: "TJ", name: "Тажикистан" },
  { code: "TH", name: "Тайланд" },
  { code: "TW", name: "Тайвань" },
  { code: "TZ", name: "Танзани" },
  { code: "TG", name: "Того" },
  { code: "TO", name: "Тонга" },
  { code: "TT", name: "Тринидад Тобаго" },
  { code: "TV", name: "Тувалу" },
  { code: "TN", name: "Тунис" },
  { code: "TM", name: "Туркменистан" },
  { code: "TR", name: "Турк" },
  { code: "UG", name: "Уганда" },
  { code: "UA", name: "Украин" },
  { code: "UY", name: "Уругвай" },
  { code: "UZ", name: "Узбекистан" },
  { code: "FJ", name: "Фижи" },
  { code: "PH", name: "Филиппин" },
  { code: "FI", name: "Финлянд" },
  { code: "FR", name: "Франц" },
  { code: "KP", name: "Хойд Солонгос" },
  { code: "MK", name: "Хойд Македон" },
  { code: "HR", name: "Хорват" },
  { code: "CN", name: "Хятад" },
  { code: "TD", name: "Чад" },
  { code: "CZ", name: "Чехи" },
  { code: "CL", name: "Чили" },
  { code: "SE", name: "Швед" },
  { code: "CH", name: "Швейцари" },
  { code: "NZ", name: "Шинэ Зеланд" },
  { code: "EC", name: "Эквадор" },
  { code: "GQ", name: "Экваторын Гвиней" },
  { code: "ER", name: "Эритрей" },
  { code: "EE", name: "Эстони" },
  { code: "ET", name: "Этиоп" },
  { code: "ZA", name: "Өмнөд Африк" },
  { code: "KR", name: "Өмнөд Солонгос" },
  { code: "SS", name: "Өмнөд Судан" },
  { code: "GB", name: "Их Британи" },
  { code: "JM", name: "Ямайк" },
  { code: "JP", name: "Япон" },
];

export const COUNTRIES: Country[] = RAW_COUNTRIES.map((c) => ({
  ...c,
  flagUrl: flagUrl(c.code),
})).sort((a, b) => a.name.localeCompare(b.name, "mn"));
